name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - terraform/**/*
  pull_request:
    branches:
      - main
    paths:
      - terraform/**/*

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      tf_actions_working_dir: terraform
      TF_VAR_github_token: ${{ secrets.TF_VAR_github_token }}
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate
      - name: Terraform Plan
        id: plan
        run: terraform plan
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
